#!/usr/bin/env bash
#
# Debian Packaging Scripts
# Copyright (C) 2002-2024 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com

LIBRARY_PACKAGES="libneat0"


find debian/ -maxdepth 1 -name "*.symbols" | xargs --no-run-if-empty rm -f

echo ""
echo "Creating binary package ..."
echo ""

./autogen.sh && debuild -b -us -uc || exit 1


for LIBRARY_PACKAGE in $LIBRARY_PACKAGES ; do
   echo ""
   echo "Creating symbols for library package $LIBRARY_PACKAGE ..."
   echo ""

   # Symbol file generation according How-To at:
   # http://swik.net/Ubuntu/Planet+Ubuntu/Dmitrijs+Ledkovs%3A+Lintian+no-symbols-control-file/d4q9h

   find . -maxdepth 1 -name "dpkg-gensymbols*" | xargs --no-run-if-empty rm -f

   echo "dpkg-gensymbols -p$LIBRARY_PACKAGE -Pdebian/$LIBRARY_PACKAGE | patch -p0"
   dpkg-gensymbols -p$LIBRARY_PACKAGE -Pdebian/$LIBRARY_PACKAGE | patch -p0 || exit 1

   # Replace C++ symbols which are different on 32- and 64-bit systems
   ./replace-cpp-symbols <dpkg-gensymbols* >debian/$LIBRARY_PACKAGE.symbols || exit 1

   # Strip off ubuntu version!
   perl -pi -e 's/-\d.*//' debian/$LIBRARY_PACKAGE.symbols || exit 1
done

echo ""
echo "Done."
