#!/bin/bash -e
#
# Travis CI Scripts
# Copyright (C) 2018-2019 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@iem.uni-due.de


# ###### Linux ##############################################################
if [ "$TRAVIS_OS_NAME" = "linux" ] ; then
   sudo docker rm -f ubuntu-test || true
   sudo docker run -d \
      --name ubuntu-test \
      --tmpfs /var/cache/pbuilder:rw,exec,dev,size=4g \
      --cap-add=SYS_ADMIN --cap-add=NET_ADMIN \
      --security-opt apparmor:unconfined \
      -v $(pwd):/travis -w /travis \
      $DOCKER tail -f /dev/null
   sudo docker ps

# ###### Other ##############################################################
elif [ "$TRAVIS_OS_NAME" = "osx" ] ; then
   brew update
   brew install ...

# ###### Error ##############################################################
else
   echo >&2 "ERROR: Invalid setting of TRAVIS_OS_NAME=$TRAVIS_OS_NAME"
   exit 1
fi
