#!/bin/bash -e
#
# Travis CI Scripts
# Copyright (C) 2018-2019 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@iem.uni-due.de


# ###### Linux ##############################################################
if [ "$TRAVIS_OS_NAME" = "linux" ] ; then
   if [ "$TOOL" = "compile" ] ; then
      sudo docker exec -t ubuntu-test bash -c "echo OPTIONS: CC=$COMPILER_C CXX=$COMPILER_CXX"
      sudo docker exec -t ubuntu-test bash -c "env CC=$COMPILER_C CXX=$COMPILER_CXX cmake ."
      sudo docker exec -t ubuntu-test bash -c "make VERBOSE=1"

   elif [ "$TOOL" = "pbuilder" ] ; then
     sudo docker exec -t ubuntu-test bash -c "sed -e 's/SKIP_PACKAGE_SIGNING=0/SKIP_PACKAGE_SIGNING=1/g' -i debian.conf"
     sudo docker exec -t ubuntu-test bash -c "env LANG=C.UTF-8 eatmydata ./build-deb"

   elif [ "$TOOL" = "mock" ] ; then
      sudo docker exec -t ubuntu-test bash -c "cat /etc/fedora-release"
      release=`sudo docker exec -t ubuntu-test bash -c "cat /etc/fedora-release | sed -e \"s/^\(.*\) release \([0-9]*\) (\(.*\))$/\2/g\""`
      release=`echo "$release" | sed -e "s/[^0-9]//g"`
      buildFor="fedora-$release-x86_64"
      echo "release=$release."
      echo "buildFor=$buildFor."
      sudo docker exec -t ubuntu-test bash -c "./make-rpm $buildFor"

   else
      echo >&2 "ERROR: Invalid setting of TOOL=$TOOL"
      exit 1
   fi

# ###### Other ##############################################################
elif [ "$TRAVIS_OS_NAME" = "osx" ] ; then
   cmake .
   make VERBOSE=1

# ###### Error ##############################################################
else
   echo >&2 "ERROR: Invalid setting of TRAVIS_OS_NAME=$TRAVIS_OS_NAME"
   exit 1
fi
