#!/bin/bash -e

export TRAVIS_OS_NAME="linux"


# export DOCKER="debian:stretch"
# export VARIANT="debian"
# export TOOL="pbuilder"

export DOCKER="ubuntu:bionic"
export VARIANT="ubuntu"
export TOOL="compile"

# export DOCKER="fedora:29"
# export VARIANT="fedora"
# export TOOL="mock"


SCRIPTS="before-install install build"
# SCRIPTS="install"

for script in $SCRIPTS ; do
   sudo env \
      TRAVIS_OS_NAME="$TRAVIS_OS_NAME" \
      DOCKER="$DOCKER" \
      VARIANT="$VARIANT" \
      TOOL="$TOOL" ci/${script}
done
