# GitHub Actions Scripts
# Copyright (C) 2021-2026 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

name: FreeBSD CI Tests

on:
  push:
    branches:
      - master
      - main
      - dreibh/github-actions

jobs:

  # #########################################################################
  # #### Build from Sources                                              ####
  # #########################################################################
  Build:

    # ###### Build matrix ###################################################
    strategy:
      matrix:
        include:
          # ====== FreeBSD ==================================================
          - label: "FreeBSD 15.0 with Clang/x86_64"
            release: "15.0"
            cc: clang
            cxx: clang++
          - label: "FreeBSD 14.4 with Clang/x86_64"
            release: "14.4"
            cc: clang
            cxx: clang++

    # ###### Build commands #################################################
    name: ${{ matrix.label }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Test in FreeBSD
        id: test
        uses: vmactions/freebsd-vm@v1
        with:
          release: ${{ matrix.release }}
          usesh: true
          run: |
            ASSUME_ALWAYS_YES=yes pkg install -y bash
            CC=${{ matrix.cc }} CXX=${{ matrix.cxx }} ci/ci-setup   compile
            CC=${{ matrix.cc }} CXX=${{ matrix.cxx }} ci/ci-install compile
            CC=${{ matrix.cc }} CXX=${{ matrix.cxx }} ci/ci-build   compile


  # #########################################################################
  # #### Multi-Architecture Builds                                       ####
  # #########################################################################
  Architectures:
    # ###### Build matrix ###################################################
    strategy:
      matrix:
        include:
          # ====== FreeBSD ==================================================
          - label: "FreeBSD 14.4 with Clang/ARMv8"
            release: "14.4"
            architecture: aarch64
            cc: clang
            cxx: clang++
          - label: "FreeBSD 14.4 with Clang/RISC-V"
            release: "14.4"
            architecture: riscv64
            cc: clang
            cxx: clang++

    # ###### Build commands #################################################
    name: ${{ matrix.label }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Test in FreeBSD
        id: test
        uses: vmactions/freebsd-vm@v1
        with:
          release: ${{ matrix.release }}
          usesh: true
          run: |
            ASSUME_ALWAYS_YES=yes pkg install -y bash
            CC=${{ matrix.cc }} CXX=${{ matrix.cxx }} ci/ci-setup   compile
            CC=${{ matrix.cc }} CXX=${{ matrix.cxx }} ci/ci-install compile
            CC=${{ matrix.cc }} CXX=${{ matrix.cxx }} ci/ci-build   compile
